name: Generate SBOM for Pull Request

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: windows-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3

    

      - name: Generate SBOM using GitHub API
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Make sure to use a secret GitHub token
        run: |
          # Fetch the SBOM from the Dependency Graph for the current PR branch
          
          curl -H "Accept: application/vnd.github+json" ^
               -H "X-GitHub-Api-Version: 2022-11-28" ^
               https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/dependency-graph/sbom ^
               -o sbom.json


      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json
          path: sbom.json
