name: "Download SBOM from GitHub"
description: "Download the SBOM from GitHub API"
author: "valpinkman"

on:
  push
  
jobs:
  download_sbom:
    runs-on: windows-latest  # Use Windows runner

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

  
    - name: Download SBOM
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}  # Use GitHub's token directly from the environment variable
        REPO_OWNER: ${{ github.repository_owner }}  # Directly access the repository owner
        REPO_NAME: ${{ github.repository }}  # Directly access the repository name
      run: |
        Write-Host "Downloading SBOM for repository: $env:REPO_OWNER\$env:REPO_NAME"
        
        # Use the GitHub CLI to download the SBOM
        gh api `
          -H "Accept: application/vnd.github+json" `
          -H "X-GitHub-Api-Version: 2022-11-28" `
          /repos/$env:REPO_OWNER/$env:REPO_NAME/dependency-graph/sbom `
          | Out-File -FilePath sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.json
