name: Generate SBOM for Pull Request

on:
  push:
    branches:
      - test-sample

jobs:
  generate-sbom:
    runs-on: windows-latest 
    steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name : install github cli
      shell: pwsh
      run: |
         choco install gh -y
         gh --version

    - name: Generate SBOM using GitHub API
      shell: pwsh
      env:
       GH_TOKEN: ${{ github.token }}
      run: |
        # Fetch the SBOM from the Dependency Graph for the current PR branch
        gh api `
          --header "Accept: application/vnd.github+json" `
          --header "X-GitHub-Api-Version: 2022-11-28" `
          /repos/${{ github.repository_owner }}/${{ github.repository }}/dependency-graph/sbom `
          | Out-File -FilePath sbom.json
          
    - name: Upload SBOM as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-json
        path: sbom.json

