name: Generate SBOM for Pull Request

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set GH_TOKEN for GitHub CLI Authentication
      run: |
        echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: Generate SBOM using GitHub API
      run: |
        # Fetch the SBOM from the Dependency Graph for the current PR branch
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/dependency-graph/sbom > sbom.json

    - name: Upload SBOM as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-json
        path: sbom.json

